# -*- coding: utf-8 -*-
"""Competitive_Insight_Extractor_V1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bcirjCte-Pt5y2HbkbDHsavWx5Q_2lKY
"""

# Cell 1: Installation
!pip install google-genai
!pip install pytubefix  # Install the fixed, updated version

# Cell 2: Secure API Key Setup
import os
from google.colab import userdata

# Retrieve key securely from Colab secrets
os.environ['GEMINI_API_KEY'] = userdata.get('GEMINI_API_KEY')
print("API Key loaded securely.")

# Cell 3: Competitive Insight Extractor Script

# Imports and Client Initialization
import os
from google import genai
from pytubefix import YouTube # Updated: For metadata retrieval

# Initialize the Gemini Client
try:
    # The client automatically uses the GEMINI_API_KEY from the environment
    client = genai.Client()
except Exception as e:
    print(f"Error initializing client: {e}")
    print("Please ensure your GEMINI_API_KEY is set correctly in the previous cell.")
    exit()

# --- 1. Metadata Retrieval Function ---
def get_youtube_metadata(url):
    """Fetches key metadata fields from a YouTube video URL using pytube."""
    try:
        yt = YouTube(url)
        # Calculate duration in minutes for better business reporting
        duration_minutes = round(yt.length / 60)

        return {
            "title": yt.title,
            "channel_name": yt.author,
            "duration_minutes": duration_minutes,
            "publish_date": yt.publish_date.strftime("%Y-%m-%d")
        }
    except Exception as e:
        return {"title": "Metadata Error", "channel_name": "N/A", "duration_minutes": "N/A", "publish_date": "N/A"}


# --- 2. Your Custom Inputs ---
# Replace with a video from a competitor, industry expert, or potential partner
youtube_url_to_summarize = "https://www.youtube.com/watch?v=r5iRGvRbHpk&t=10s" # Example URL
target_model = "gemini-2.5-flash" # The fast, multimodal model

# Retrieve all metadata once
metadata = get_youtube_metadata(youtube_url_to_summarize)


# --- 3. The Advanced Competitive Analysis Prompt ---
# Role: Senior Competitive Analyst (focused, constrained, and high-value)
summary_prompt = (
    "You are a **Senior Competitive Analyst** compiling a fast-read briefing for the CEO. "
    "Your task is to analyze the entire content of the provided YouTube video and extract actionable, strategic insights focused *only* on the competitor or market position demonstrated."
    "\n\n--- INSTRUCTIONS ---\n"
    "1. **Strictly Ignore** all promotional content, personal anecdotes, and calls to action (like 'subscribe')."
    "2. **Focus:** Prioritize quantifiable data, unique selling points, and identified market gaps."
    "3. **Tone:** Maintain a formal, objective, and high-stakes business tone."
    "\n\n--- REQUIRED STRUCTURE (Use Markdown) ---\n"
    "## Competitor Strategic Analysis Brief\n\n"
    "1. **Core Positioning & Message (USP):** A single paragraph (max 50 words) that precisely identifies the primary message and unique selling proposition (USP) the presenter emphasizes.\n"
    "2. **Quantified Data & Metrics:** A bulleted list (minimum 3, maximum 5 points) of all specific, quantifiable metrics, financial figures, or growth rates mentioned in the video. If no metrics are present, state: 'No Quantified Metrics Mentioned.'\n"
    "3. **Identified Weaknesses & Market Gaps:** A bulleted list of 2-3 specific product flaws, market gaps, or strategic vulnerabilities mentioned or implied by the presenter's focus.\n"
    "4. **Urgent Strategic Recommendation:** A single-sentence, high-priority recommendation for our executive team based on the competitor's demonstrated strategy.\n"
)

# --- 4. API Call ---
print(f"Sending request to Gemini for: {metadata['title']}. Duration: {metadata['duration_minutes']} minutes.")
print("Processing analysis, this may take a moment...")

response = client.models.generate_content(
    model=target_model,
    contents=[
        {
            "parts": [
                {"text": summary_prompt},
                # Pass the YouTube URL as multimodal file data
                {"file_data": {"file_uri": youtube_url_to_summarize}},
            ]
        }
    ],
)

# --- 5. Print Final Output ---
print("\n" + "="*80)
print(f"| COMPETITIVE INSIGHT EXTRACTOR REPORT | DATE: {metadata['publish_date']} |")
print(f"| SOURCE: {metadata['channel_name']} ({metadata['duration_minutes']} min) |")
print("="*80)
print(response.text)
print("\n" + "-"*80)
print(f"Source URL: {youtube_url_to_summarize}")